// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | BilanSlice
  | PrioritiesSlice
  | ContactSlice
  | TeamSlice
  | HeroSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Item in *Bilan → Default → Primary → Bilan Items → Actions avec photos*
 */
export interface BilanSliceDefaultPrimaryBilanItemsActionDetailsItem {
  /**
   * Titre de l'action field in *Bilan → Default → Primary → Bilan Items → Actions avec photos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: Rénovation de la place du village
   * - **API ID Path**: bilan.default.primary.bilan_items[].action_details[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description de l'action field in *Bilan → Default → Primary → Bilan Items → Actions avec photos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: bilan.default.primary.bilan_items[].action_details[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Photo de l'action field in *Bilan → Default → Primary → Bilan Items → Actions avec photos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bilan.default.primary.bilan_items[].action_details[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * text field in *Bilan → Default → Primary → Bilan Items → Actions avec photos*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texte
   * - **API ID Path**: bilan.default.primary.bilan_items[].action_details[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Item in *Bilan → Default → Primary → Bilan Items*
 */
export interface BilanSliceDefaultPrimaryBilanItemsItem {
  /**
   * Icône field in *Bilan → Default → Primary → Bilan Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choisir une icône
   * - **API ID Path**: bilan.default.primary.bilan_items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    | "enfance_jeunesse_seniors"
    | "environnement_cadre_vie"
    | "soutien_economique_patrimoine"
    | "solidarite_social_vie_pratique"
    | "securite_prevention"
    | "sport_associations"
  >;

  /**
   * Title field in *Bilan → Default → Primary → Bilan Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre du thème
   * - **API ID Path**: bilan.default.primary.bilan_items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Bilan → Default → Primary → Bilan Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description courte du thème
   * - **API ID Path**: bilan.default.primary.bilan_items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Actions (ancien format - optionnel) field in *Bilan → Default → Primary → Bilan Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Liste des actions réalisées
   * - **API ID Path**: bilan.default.primary.bilan_items[].actions
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  actions: prismic.RichTextField;

  /**
   * Actions avec photos field in *Bilan → Default → Primary → Bilan Items*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bilan.default.primary.bilan_items[].action_details[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  action_details: prismic.NestedGroupField<
    Simplify<BilanSliceDefaultPrimaryBilanItemsActionDetailsItem>
  >;

  /**
   * Photo de thématique field in *Bilan → Default → Primary → Bilan Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bilan.default.primary.bilan_items[].thematic_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thematic_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Bilan → Default → Primary*
 */
export interface BilanSliceDefaultPrimary {
  /**
   * Section Title field in *Bilan → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Bilan du Mandat
   * - **API ID Path**: bilan.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_title: prismic.RichTextField;

  /**
   * Section Description field in *Bilan → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Decouvrez les realisations de notre mandat
   * - **API ID Path**: bilan.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * Texte d'introduction field in *Bilan → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texte d'introduction avant les thématiques...
   * - **API ID Path**: bilan.default.primary.introduction_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  introduction_text: prismic.RichTextField;

  /**
   * Bilan Items field in *Bilan → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bilan.default.primary.bilan_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  bilan_items: prismic.GroupField<
    Simplify<BilanSliceDefaultPrimaryBilanItemsItem>
  >;

  /**
   * CTA Text field in *Bilan → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: En savoir plus
   * - **API ID Path**: bilan.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *Bilan → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: #contact
   * - **API ID Path**: bilan.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_link: prismic.KeyTextField;
}

/**
 * Default variation for Bilan Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BilanSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BilanSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Bilan*
 */
type BilanSliceVariation = BilanSliceDefault;

/**
 * Bilan Shared Slice
 *
 * - **API ID**: `bilan`
 * - **Description**: Section bilan du mandat avec realisations et images
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BilanSlice = prismic.SharedSlice<"bilan", BilanSliceVariation>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Section Title field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Contactez-nous
   * - **API ID Path**: contact.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_title: prismic.RichTextField;

  /**
   * Section Description field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Une question ? N'hésitez pas à nous écrire
   * - **API ID Path**: contact.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * Submit Button Text field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Envoyer
   * - **API ID Path**: contact.default.primary.submit_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_button_text: prismic.KeyTextField;

  /**
   * Email field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: contact@example.com
   * - **API ID Path**: contact.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +33 1 23 45 67 89
   * - **API ID Path**: contact.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact form section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Titre principal
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description ou slogan
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Background Image (Desktop) field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Background Image (Mobile) field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image_mobile
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image_mobile: prismic.ImageField<never>;

  /**
   * Logo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * CTA Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Découvrir notre équipe
   * - **API ID Path**: hero.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero section with title, description, and optional background
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Priorities → Default → Primary → Priorities*
 */
export interface PrioritiesSliceDefaultPrimaryPrioritiesItem {
  /**
   * Icon field in *Priorities → Default → Primary → Priorities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 🌱 (emoji ou texte)
   * - **API ID Path**: priorities.default.primary.priorities[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * Title field in *Priorities → Default → Primary → Priorities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Titre de la priorité
   * - **API ID Path**: priorities.default.primary.priorities[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Priorities → Default → Primary → Priorities*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description détaillée de la priorité
   * - **API ID Path**: priorities.default.primary.priorities[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Priorities → Default → Primary*
 */
export interface PrioritiesSliceDefaultPrimary {
  /**
   * Section Title field in *Priorities → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Nos Priorités pour 2026
   * - **API ID Path**: priorities.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_title: prismic.RichTextField;

  /**
   * Section Description field in *Priorities → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description de nos engagements pour La Chapelle de la Tour
   * - **API ID Path**: priorities.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * Priorities field in *Priorities → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: priorities.default.primary.priorities[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  priorities: prismic.GroupField<
    Simplify<PrioritiesSliceDefaultPrimaryPrioritiesItem>
  >;

  /**
   * CTA Text field in *Priorities → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nous contacter
   * - **API ID Path**: priorities.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;
}

/**
 * Default variation for Priorities Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PrioritiesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PrioritiesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Priorities*
 */
type PrioritiesSliceVariation = PrioritiesSliceDefault;

/**
 * Priorities Shared Slice
 *
 * - **API ID**: `priorities`
 * - **Description**: Section des priorités de la campagne électorale
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PrioritiesSlice = prismic.SharedSlice<
  "priorities",
  PrioritiesSliceVariation
>;

/**
 * Item in *Team → Default → Primary → Team Members*
 */
export interface TeamSliceDefaultPrimaryTeamMembersItem {
  /**
   * Name field in *Team → Default → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nom complet
   * - **API ID Path**: team.default.primary.team_members[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Age field in *Team → Default → Primary → Team Members*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 35
   * - **API ID Path**: team.default.primary.team_members[].age
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  age: prismic.NumberField;

  /**
   * Role field in *Team → Default → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tête de liste, Adjoint, etc.
   * - **API ID Path**: team.default.primary.team_members[].role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Profession field in *Team → Default → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Agriculteur, Enseignant, etc.
   * - **API ID Path**: team.default.primary.team_members[].profession
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  profession: prismic.KeyTextField;

  /**
   * Localité field in *Team → Default → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: La Chapelle-du-Bard
   * - **API ID Path**: team.default.primary.team_members[].localite
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  localite: prismic.KeyTextField;

  /**
   * Photo field in *Team → Default → Primary → Team Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_members[].photo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  photo: prismic.ImageField<never>;

  /**
   * Bio field in *Team → Default → Primary → Team Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Courte biographie
   * - **API ID Path**: team.default.primary.team_members[].bio
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Section Title field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Notre équipe
   * - **API ID Path**: team.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_title: prismic.RichTextField;

  /**
   * Section Description field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description de la liste
   * - **API ID Path**: team.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * Group Photo field in *Team → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.group_photo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  group_photo: prismic.ImageField<never>;

  /**
   * Team Introduction field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texte d'introduction de la liste...
   * - **API ID Path**: team.default.primary.team_intro
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  team_intro: prismic.RichTextField;

  /**
   * Team Members field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_members[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  team_members: prismic.GroupField<
    Simplify<TeamSliceDefaultPrimaryTeamMembersItem>
  >;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team members section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BilanSlice,
      BilanSliceDefaultPrimaryBilanItemsActionDetailsItem,
      BilanSliceDefaultPrimaryBilanItemsItem,
      BilanSliceDefaultPrimary,
      BilanSliceVariation,
      BilanSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      PrioritiesSlice,
      PrioritiesSliceDefaultPrimaryPrioritiesItem,
      PrioritiesSliceDefaultPrimary,
      PrioritiesSliceVariation,
      PrioritiesSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryTeamMembersItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
    };
  }
}
