// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bilan: dynamic(() => import("./Summary")),
  contact: dynamic(() => import("./Contact")),
  events: dynamic(() => import("./Events")),
  hero: dynamic(() => import("./Hero")),
  priorities: dynamic(() => import("./Priorities")),
  team: dynamic(() => import("./Team")),
};
