// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  priorities: dynamic(() => import("./Priorities")),
  team: dynamic(() => import("./Team")),
};
